# BAG OF WORDS

In [29]:
from sklearn.feature_extraction.text import CountVectorizer

train_x=['I love the book','this is a great book','the fit is great',' i love the shoes']


In [26]:
vectorizer=CountVectorizer(binary=True)
train_x = vectorizer.fit_transform(train_x)
print(vectors[0])
print(vectorizer.get_feature_names_out())
print(vectors.toarray())

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 3 stored elements and shape (1, 8)>
  Coords	Values
  (0, 4)	1
  (0, 6)	1
  (0, 0)	1
['book' 'fit' 'great' 'is' 'love' 'shoes' 'the' 'this']
[[1 0 0 0 1 0 1 0]
 [1 0 1 1 0 0 0 1]
 [0 1 1 1 0 0 1 0]
 [0 0 0 0 1 1 1 0]]


In [10]:
class Category:
    BOOKS = 'BOOKS'
    CLOTHING = 'CLOTHING'
    
train_y=[Category.BOOKS,Category.BOOKS,Category.CLOTHING , Category.CLOTHING]


In [27]:
from sklearn import svm 
clf_svm = svm.SVC(kernel='linear')
clf_svm.fit(train_x, train_y)  

SVC(kernel='linear')

In [14]:
test_x = vectorizer.transform(['these shoes look ok'])
clf_svm.predict(test_x)

array(['CLOTHING'], dtype='<U8')

# WORD VECTORS 


In [17]:
pip install spacy

   ---------------------------------------- 0.0/11.8 MB ? eta -:--:--
   - -------------------------------------- 0.5/11.8 MB 2.8 MB/s eta 0:00:05
   --- ------------------------------------ 1.0/11.8 MB 2.8 MB/s eta 0:00:04
   ----- ---------------------------------- 1.6/11.8 MB 2.7 MB/s eta 0:00:04
   ------- -------------------------------- 2.1/11.8 MB 2.7 MB/s eta 0:00:04
   -------- ------------------------------- 2.6/11.8 MB 2.7 MB/s eta 0:00:04
   ---------- ----------------------------- 3.1/11.8 MB 2.7 MB/s eta 0:00:04
   ------------ --------------------------- 3.7/11.8 MB 2.6 MB/s eta 0:00:04
   -------------- ------------------------- 4.2/11.8 MB 2.6 MB/s eta 0:00:03
   ---------------- ----------------------- 4.7/11.8 MB 2.6 MB/s eta 0:00:03
   ----------------- ---------------------- 5.2/11.8 MB 2.6 MB/s eta 0:00:03
   ------------------- -------------------- 5.8/11.8 MB 2.6 MB/s eta 0:00:03
   --------------------- ------------------ 6.3/11.8 MB 2.5 MB/s eta 0:00:03
   ---

  You can safely remove it manually.
  You can safely remove it manually.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
numba 0.61.0 requires numpy<2.2,>=1.24, but you have numpy 2.2.5 which is incompatible.
tensorflow 2.19.0 requires numpy<2.2.0,>=1.26.0, but you have numpy 2.2.5 which is incompatible.


In [19]:
!python -m spacy download en_core_web_md

     ---------------------------------------- 0.0/33.5 MB ? eta -:--:--
     ---------------------------------------- 0.3/33.5 MB ? eta -:--:--
      --------------------------------------- 0.8/33.5 MB 2.6 MB/s eta 0:00:13
     - -------------------------------------- 1.3/33.5 MB 2.6 MB/s eta 0:00:13
     -- ------------------------------------- 1.8/33.5 MB 2.6 MB/s eta 0:00:12
     -- ------------------------------------- 2.4/33.5 MB 2.6 MB/s eta 0:00:12
     --- ------------------------------------ 3.1/33.5 MB 2.7 MB/s eta 0:00:12
     ---- ----------------------------------- 3.7/33.5 MB 2.7 MB/s eta 0:00:12
     ----- ---------------------------------- 4.2/33.5 MB 2.7 MB/s eta 0:00:11
     ----- ---------------------------------- 4.7/33.5 MB 2.6 MB/s eta 0:00:11
     ----- ---------------------------------- 4.7/33.5 MB 2.6 MB/s eta 0:00:11
     ------ --------------------------------- 5.5/33.5 MB 2.5 MB/s eta 0:00:12
     ------- -------------------------------- 6.0/33.5 MB 2.5 MB/s

In [25]:
import spacy
nlp = spacy.load('en_core_web_md')

In [31]:
print(train_x)

['I love the book', 'this is a great book', 'the fit is great', ' i love the shoes']


In [45]:

docs = [nlp(text) for text in train_x]
train_x_word_vectors =[x.vector for x in docs]


In [46]:
clf_svm_wv =svm.SVC(kernel='linear')
clf_svm_wv.fit(train_x_word_vectors, train_y)

SVC(kernel='linear')

In [54]:
test_x =['i love the shorts']
test_docs =[nlp(text) for text in test_x]
test_x_word_vectors =[x.vector for x in test_docs]
clf_svm_wv.predict(test_x_word_vectors)

array(['CLOTHING'], dtype='<U8')